kubectl delete configmap chainmaker-1-config 
kubectl delete configmap chainmaker-2-config 
kubectl delete configmap chainmaker-3-config 
kubectl delete configmap chainmaker-4-config 
kubectl delete secret  chainmaker-ca 
kubectl	delete secret  chainmaker-1-node 
kubectl	delete secret  chainmaker-2-node 
kubectl	delete secret  chainmaker-3-node 
kubectl	delete secret  chainmaker-4-node 
kubectl	delete secret  chainmaker-1-user 
kubectl	delete secret  chainmaker-2-user 
kubectl	delete secret  chainmaker-3-user 
kubectl	delete secret  chainmaker-4-user 
