kubectl delete configmaps chainmaker-1-config 
kubectl delete configmaps chainmaker-2-config 
kubectl delete configmaps chainmaker-3-config 
kubectl delete configmaps chainmaker-4-config 
kubectl delete secrets  chainmaker-ca 
kubectl	delete secrets  chainmaker-1-node 
kubectl	delete secrets  chainmaker-2-node 
kubectl	delete secrets  chainmaker-3-node 
kubectl	delete secrets  chainmaker-4-node 
kubectl	delete secrets  chainmaker-1-user 
kubectl	delete secrets  chainmaker-2-user 
kubectl	delete secrets  chainmaker-3-user 
kubectl	delete secrets  chainmaker-4-user 
