log:
  config_file: ""
  system:
    log_level_default: INFO
    log_levels:
      core: INFO
      net: INFO
    file_path: /home/heyue/logs/system.log
    max_age: 365
    rotation_time: 1
    log_in_console: true
    show_color: true
  brief:
    log_level_default: INFO
    log_levels: {}
    file_path: /home/heyue/logs/brief.log
    max_age: 365
    rotation_time: 1
    log_in_console: true
    show_color: true
  event:
    log_level_default: INFO
    log_levels: {}
    file_path: /home/heyue/logs/event.log
    max_age: 365
    rotation_time: 1
    log_in_console: true
    show_color: true
net:
  provider: LibP2P
  listen_addr: /ip4/0.0.0.0/tcp/11300
  peer_stream_pool_size: 0
  max_peer_count_allow: 0
  peer_elimination_strategy: 0
  seeds:
  - /dns4/chainmaker-1/tcp/11300/p2p/Qmav85Dzk3qC4FpRBo3EtKYwbqLoAfoW9BxGf7nnpD6FzF
  - /dns4/chainmaker-2/tcp/11300/p2p/QmVZd383aTenK6vjcZiTrkrZuhfG7E2HwEjKALKQoGhwSz
  - /dns4/chainmaker-3/tcp/11300/p2p/QmSUxNMZdBAHMgo6JEATxrGAsG5wpfpeHuWEy8ru9kGDZC
  - /dns4/chainmaker-4/tcp/11300/p2p/QmY8VHV8U2ETeLUXZRGJQqSk3kzw9NyYDNJ99gT9NQmLdg
  tls:
    enabled: true
    priv_key_file: /home/heyue/node/consensus1.tls.key
    cert_file: /home/heyue/node/consensus1.tls.crt
  blacklist:
    addresses: []
    node_ids: []
  custom_chain_trust_roots: []
node:
  type: full
  cert_file: /home/heyue/node/consensus1.sign.crt
  priv_key_file: /home/heyue/node/consensus1.sign.key
  priv_key_password: ""
  auth_type: ""
  pkcs11:
    enabled: false
    library: ""
    label: ""
    password: ""
    session_cache_size: 10
    hash: SHA256
  node_id: ""
  org_id: wx-org1.chainmaker.org
  signer_cache_size: 1000
  cert_cache_size: 1000
rpc:
  provider: grpc
  port: 12300
  tls:
    mode: twoway
    priv_key_file: /home/heyue/node/consensus1.tls.key
    cert_file: /home/heyue/node/consensus1.tls.crt
    test_client_priv_key_file: ""
    test_client_cert_file: ""
  ratelimit:
    token_per_second: -1
    token_bucket_size: -1
  subscriber:
    ratelimit:
      token_per_second: 100
      token_bucket_size: 100
  check_chain_conf_trust_roots_change_interval: 60
blockchain:
- chainid: chain1
  genesis: /home/heyue/config/bc1.yml
storage:
  store_path: /home/heyue/data/ledgerData
  db_prefix: ""
  write_buffer_size: 0
  bloom_filter_bits: 0
  block_write_buffer_size: 0
  disable_historydb: false
  disable_resultdb: false
  disable_contract_eventdb: true
  logdb_write_async: false
  blockdb_config:
    provider: leveldb
    leveldb_config:
      store_path: /home/heyue/data/blocks
      write_buffer_size: 0
      bloom_filter_bits: 0
      block_write_buffer_size: 0
    sqldb_config: null
  statedb_config:
    provider: leveldb
    leveldb_config:
      store_path: /home/heyue/data/state
      write_buffer_size: 0
      bloom_filter_bits: 0
      block_write_buffer_size: 0
    sqldb_config: null
  historydb_config:
    provider: leveldb
    leveldb_config:
      store_path: /home/heyue/data/history
      write_buffer_size: 0
      bloom_filter_bits: 0
      block_write_buffer_size: 0
    sqldb_config: null
  resultdb_config:
    provider: leveldb
    leveldb_config:
      store_path: /home/heyue/data/result
      write_buffer_size: 0
      bloom_filter_bits: 0
      block_write_buffer_size: 0
    sqldb_config: null
  contract_eventdb_config:
    provider: sql
    leveldb_config: null
    sqldb_config:
      sqldb_type: mysql
      dsn: root:password@tcp(127.0.0.1:3306)/
      max_idle_conns: 0
      max_open_conns: 0
      conn_max_lifetime: 0
      sqllog_mode: ""
      sql_verifier: ""
      db_prefix: ""
  unarchive_block_height: 300000
txpool:
  pool_type: ""
  max_txpool_size: 50000
  max_config_txpool_size: 10
  is_metrics: false
  performance: false
  batch_max_size: 30000
  batch_create_timeout: 200
  cache_flush_ticker: 0
  cache_threshold_count: 0
  cache_flush_timeout: 0
  add_tx_channel_size: 0
sync:
  broadcast_time: 0
  block_pool_size: 0
  wait_time_requested: 0
  batch_Size_from_one_node: 0
  process_block_tick: 0
  node_status_tick: 0
  liveness_tick: 0
  scheduler_tick: 0
  req_time_threshold: 0
  data_detection_tick: 0
spv:
  refresh_reqcache_mils: 0
  message_cahche_size: 0
  resync_check_interval_mils: 0
  sync_timeout_mils: 0
  reqsync_blocknum: 0
  max_reqsync_blocknum: 0
  peer_active_time: 0
debug:
  is_cli_open: false
  is_http_open: false
  is_proposer: false
  is_not_rwset_check: false
  is_concur_propose: false
  is_concur_verify: false
  is_solo: false
  is_halt_propose: false
  is_skip_access_control: false
  is_trace_memory_usage: false
  is_propose_duplicately: false
  is_propose_multinode_duplicately: false
  is_proposal_old_height: false
  is_prevote_duplicately: false
  is_prevote_old_height: false
  is_prevote_lost: false
  is_precommit_duplicately: false
  is_precommit_old_height: false
  is_propose_lost: false
  is_propose_delay: false
  is_prevote_delay: false
  is_precommit_lost: false
  is_prevcommit_delay: false
  is_commit_without_publish: false
  is_prevote_invalid: false
  is_precommit_invalid: false
  is_modify_tx_payload: false
  is_extreme: false
  use_net_msg_compression: false
  is_net_insecurity: false
pprof:
  enabled: false
  port: 24330
monitor:
  enabled: true
  port: 14320
core:
  evidence: false
scheduler:
  rwset_log: false
